version: "3"

services:
  app:
    build: .
    tty: true
    volumes:
      - ./app:/app
    links:
      - postgresql
    ports:
      - '3000:3000'
    environment:
      POSTGRE_SQL_HOST: postgresql
  postgresql:
    image: 'postgres:11.10'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'

